{"uid":"1ff583216cf74d3","name":"Creating a new facility in desktop app","fullName":"Creating a facility: Creating a new facility in desktop app","historyId":"b36264fabe4967c637547591384f5ad4","time":{"start":1704100373879,"stop":1704100436690,"duration":62811},"status":"broken","statusMessage":"NameError: name 'datetime' is not defined\n","statusTrace":"  File \"/home/runner/.local/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Facility.py\", line 78, in adding_a_new_facility\n    current_datetime = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"NameError: name 'datetime' is not defined\n","statusTrace":"  File \"/home/runner/.local/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Facility.py\", line 78, in adding_a_new_facility\n    current_datetime = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","steps":[{"name":"Given User is on Desktop application","time":{"start":1704100375085,"stop":1704100401655,"duration":26570},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When User navigate to the facility section","time":{"start":1704100401659,"stop":1704100413985,"duration":12326},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then User creates a new  facility","time":{"start":1704100413986,"stop":1704100434526,"duration":20540},"status":"broken","statusMessage":"NameError: name 'datetime' is not defined\n","statusTrace":"  File \"/home/runner/.local/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Facility.py\", line 78, in adding_a_new_facility\n    current_datetime = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","steps":[],"attachments":[{"uid":"69ed0ea7d46bef2c","name":".table","source":"69ed0ea7d46bef2c.csv","type":"text/csv","size":120}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"d6837823b3982827","name":"Screenshot : creating_a_new_facility_in_desktop_app","source":"d6837823b3982827.png","type":"image/png","size":91751},{"uid":"1bdab68505ea21c","name":"Video : Creating a new facility in desktop app","source":"1bdab68505ea21c.webm","type":"video/webm","size":2714352},{"uid":"623ab9b84a924f5f","name":"Trace viewer logs","source":"623ab9b84a924f5f.zip","type":"application/zip","size":21838704}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":4,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Creating a facility"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"23f0305448d33660","reportUrl":"https://manas-143.github.io/MyMedGas/27//#testresult/23f0305448d33660","status":"broken","statusDetails":"NameError: name 'datetime' is not defined\n","time":{"start":1704098269485,"stop":1704098332665,"duration":63180}}]},"tags":[]},"source":"1ff583216cf74d3.json","parameterValues":[]}