{"uid":"23f0305448d33660","name":"Creating a new facility in desktop app","fullName":"Creating a facility: Creating a new facility in desktop app","historyId":"b36264fabe4967c637547591384f5ad4","time":{"start":1704098269485,"stop":1704098332665,"duration":63180},"status":"broken","statusMessage":"NameError: name 'datetime' is not defined\n","statusTrace":"  File \"/home/runner/.local/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Facility.py\", line 78, in adding_a_new_facility\n    current_datetime = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"NameError: name 'datetime' is not defined\n","statusTrace":"  File \"/home/runner/.local/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Facility.py\", line 78, in adding_a_new_facility\n    current_datetime = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","steps":[{"name":"Given User is on Desktop application","time":{"start":1704098270716,"stop":1704098297453,"duration":26737},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When User navigate to the facility section","time":{"start":1704098297453,"stop":1704098309955,"duration":12502},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then User creates a new  facility","time":{"start":1704098309956,"stop":1704098330506,"duration":20550},"status":"broken","statusMessage":"NameError: name 'datetime' is not defined\n","statusTrace":"  File \"/home/runner/.local/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Facility.py\", line 78, in adding_a_new_facility\n    current_datetime = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","steps":[],"attachments":[{"uid":"576ef61d2f1cad59","name":".table","source":"576ef61d2f1cad59.csv","type":"text/csv","size":120}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"c9b210f004059efb","name":"Screenshot : creating_a_new_facility_in_desktop_app","source":"c9b210f004059efb.png","type":"image/png","size":91751},{"uid":"481c3dca36973a13","name":"Video : Creating a new facility in desktop app","source":"481c3dca36973a13.webm","type":"video/webm","size":2659082},{"uid":"245495b21512cabf","name":"Trace viewer logs","source":"245495b21512cabf.zip","type":"application/zip","size":21796789}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":4,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Creating a facility"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"23f0305448d33660.json","parameterValues":[]}